version: '3.8'
services:
  music-api:
    build: ..
    ports:
      - "8000:8000"
    environment:
      - RAY_ADDRESS=auto
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
