apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-api
  template:
    metadata:
      labels:
        app: music-api
    spec:
      containers:
        - name: music-api
          image: your-registry/music-api:latest
          env:
            - name: RAY_ADDRESS
              value: "auto"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: music-api
spec:
  type: ClusterIP
  selector:
    app: music-api
  ports:
    - port: 80
      targetPort: 8000
